import LocalizedStrings from 'react-localization'

export let strings = new LocalizedStrings({
  en:{
    back_to_album_search:"back to album search",
    edit:"edit",
    search:"search",
    result:"{0} result",
    results:"{0} results",
    artist:"Artist",
    album:"Album",
    track:"Track",
    title:"Title",
    length:"Length",
    no:"No.",
    track_number:"Track number",
    track_title:"Track title",
    mm:"MM",
    ss:"SS",
    add_track:"add track",
    remove_track:"remove track",
    move_up:"move up",
    move_down:"move down",
    select_artist:"-- select artist --",
    edit_artists:"edit artists",
    album_title:"album title",
    release_date:"release date",
    cover:"cover",
    add_album:"add album",
    remove_album:"remove album",
    album_removed:"Album removed: {0} - {1}",
    album_added:"Album added: {0} - {1}",
    album_already_found:"Album already found: {0} - {1}",
    page_not_found:"Page not found", 
    albums:"Albums",
    artist_title:"Artist title",
    add_artist:"Add artist",
    artist_removed:"Artist removed: {0}",
    artist_title_cannot_be_empty:"Artist title cannot be empty",
    artist_already_found:"Artist already found: {0}",
    artist_title_edited:"Artist title edited: {0} → {1}",
    artist_added:"Artist addded: {0}",
    artist_edited:"Artist edited: {0} → {1}",
    album_title_edited:"Album title edited: {0} → {1}",
    release_date_edited:"Release date edited: {0} → {1}",
    cover_cannot_be_empty:"Cover cannot be empty",
    cover_edited:"Cover edited: {0} → {1}",
    genre:"Genre",
    genres_edited:"Genres edited: {0} → {1}",
    genres:"genres",
    genre_title:"Genre title",
    add_genre:"Add genre",
    genre_removed:"Genre removed: {0}",
    genre_title_cannot_be_empty:"Genre title cannot be empty",
    genre_already_found:"Genre already found: {0}",
    genre_title_edited:"Genre title edited: {0} → {1}",
    genre_added:"Genre addded: {0}",
    genre_edited:"Genre edited: {0} → {1}",
    rating_edited:"Rating edited: {0} → {1}",
    edit_genres:"edit genres",
    empty:"empty",
    are_you_sure_you_want_to_remove_album:"Are you sure you want to remove album:\n* {0} - {1}",
    are_you_sure_you_want_to_remove_track: "Are you sure you want to remove track:\n* {0}",
    are_you_sure_you_want_to_remove_artist:"Are you sure you want to remove artist:\n* {0}",
    also_artists_all_albums_will_be_removed:"Also artist's all albums will be removed:{0}",
    are_you_sure_you_want_to_remove_genre:"Are you sure you want to remove genre:\n* {0}",
    also_genre_will_be_removed_from_all_related_albums:"Also genre's all related albums will be removed:{0}",
    track_added:"Track added: {0}",
    track_removed:"Track removed: {0}",
    track_number_edited:"Track number edited: {0} → {1}",
    track_title_cannot_be_empty:"Track title cannot be empty",
    track_title_edited:"Track title edited: {0} → {1}",
    track_minutes_cannot_be_empty:"Track minutes cannot be empty",
    track_minutes_cannot_be_negative:"Track minutes cannot be negative",
    track_minutes_maximum_value_is_99:"Track minutes maximum value is 99",
    track_length_edited:"Track length edited: {0} → {1}",
    track_seconds_cannot_be_empty:"Track seconds cannot be empty",
    track_seconds_cannot_be_negative:"Track seconds cannot be empty",
    track_seconds_maximum_value_is_59:"Track seconds maximum value is 59",
    album_title_cannot_be_empty:"Album title cannot be empty",
    release_date_cannot_be_empty:"Release date cannot be empty",
    remove:"remove",
    cancel:"cancel",
    from:"from",
    to:"to",
    rating_at_least:"rating at least",
    rating:"rating: {0}",
    unrated:"unrated"
  }
})
