import LocalizedStrings from 'react-localization'

export let strings = new LocalizedStrings({
 en:{
   back_to_album_search:"back to album search",
   edit:"edit",
   search:"Search...",
   result:"{0} result",
   results:"{0} results",
   artist:"Artist",
   album:"Album",
   track:"Track",
   title:"Title",
   length:"Length",
   no:"No.",
   track_number:"Track number",
   track_title:"Track title",
   mm:"MM",
   ss:"SS",
   add_track:"add track",
   remove_track:"remove track",
   select_artist:"-- select artist --",
   edit_artists:"edit artists",
   album_title:"album title",
   release_date:"release date",
   cover:"cover",
   add_album:"add album",
   remove_album:"remove album",
   album_removed:"Album removed: {0} - {1}",
   album_added:"Album added: {0} - {1}",
   album_already_found:"Album {0} - {1} already found",
   error:"Error: ",
   page_not_found:"Page not found",
   albums:"Albums",
   artist_title:"Artist title",
   add_artist:"Add artist",
   artist_removed:"Artist removed: {0}",
   artist_title_cannot_be_empty:"Artist title cannot be empty",
   artist_already_found:"Artist already found: {0}",
   artist_title_edited:"Artist title edited: {0} → {1}",
   artist_added:"Artist addded: {0}",
   artist_edited:"Artist edited: {0} → {1}",
   album_title_edited:"Album title edited: {0} → {1}",
   release_date_edited:"Release date edited: {0} → {1}",
   cover_cannot_be_empty:"Cover cannot be empty",
   cover_edited:"Cover edited: {0} → {1}",
   are_you_sure_you_want_to_remove_album:"Are you sure you want to remove album: {0} - {1}?",
   are_you_sure_you_want_to_remove_track: "Are you sure you want to remove track: {0}?",
   are_you_sure_you_want_to_remove_artist:"Are you sure you want to remove artist: {0}?",
   are_you_sure_you_want_to_remove_artist_and_albums:"Are you sure you want to remove artist: {0}?\n\nAlso artist's all albums will be removed:{1}",
   track_added:"Track added: {0}",
   track_removed:"Track removed: {0}",
   track_title_cannot_be_empty:"Track title cannot be empty",
   track_title_edited:"Track title edited: {0} → {1}",
   track_minutes_cannot_be_empty:"Track minutes cannot be empty",
   track_minutes_cannot_be_negative:"Track minutes cannot be negative",
   track_minutes_maximum_value_is_99:"Track minutes maximum value is 99",
   track_length_edited:"Track length edited: {0} → {1}",
   track_seconds_cannot_be_empty:"Track seconds cannot be empty",
   track_seconds_cannot_be_negative:"Track seconds cannot be empty",
   track_seconds_maximum_value_is_59:"Track seconds maximum value is 59",
   album_title_cannot_be_empty:"Album title cannot be empty",
   release_date_cannot_be_empty:"Release date cannot be empty",
   remove:"remove",
   clear_rating:"clear rating",
   star:"{0} star",
   stars:"{0} stars",
   star_at_least:"{0} star at least",
   stars_at_least:"{0} stars at least"
 }
})
